"""empty message

Revision ID: 6474b4f49d27
Revises: 
Create Date: 2023-07-28 22:32:06.336875

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6474b4f49d27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=9, scale=7), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('categories', sa.ARRAY(sa.Enum('VEGAN', 'GLUTEN_FREE', 'LACTOSE_FREE', 'VEGETARIAN', 'FINGER_FOOD', 'CAFE', name='categories')), nullable=True),
    sa.Column('posted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('places')
    op.drop_table('users')
    # ### end Alembic commands ###
